spring:
  application:
    name: Book-Management-Project
  datasource:
    url: jdbc:mysql://localhost:3306/book
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
